"""
Notification rules configuration for the NotificationProcessor Lambda.

Each rule maps a DynamoDB stream event (status change, field change, or insert)
to a notification type, target audience, and message template.

NOTE: For rules with recipient_field="EmployeeAssetIndexPK", the value stored
in DynamoDB is "EMPLOYEE#<user_id>". The processor must strip the "EMPLOYEE#"
prefix to extract the actual user ID.

NOTE: For audit-related rules, the entity_prefix uses "AUDIT#" as the SK
pattern for audit/scan records. If the actual audit SK pattern differs in the
system, update these prefixes accordingly.

NOTE: Audit status values (AUDIT_DISPUTED, AUDIT_ESCALATED, etc.) do not have
corresponding enums yet — they remain as plain strings until an Audit_Status_Enum
is added to enums.py.
"""

from utils.enums import (
    Asset_Status_Enum,
    Issue_Status_Enum,
    Notification_Type_Enum,
    Reference_Type_Enum,
    Software_Status_Enum,
    User_Role_Enum,
)

NOTIFICATION_RULES = [
    # =========================================================================
    # MANAGEMENT role-based notifications
    # =========================================================================
    {
        "trigger_type": "INSERT",
        "entity_prefix": "METADATA",
        "pk_prefix": "ASSET#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Asset_Status_Enum.ASSET_PENDING_APPROVAL,
        "notification_type": Notification_Type_Enum.ASSET_PENDING_APPROVAL,
        "target_role": User_Role_Enum.MANAGEMENT,
        "recipient_field": None,
        "title": "Asset Pending Approval",
        "message_template": "Asset {reference_id} requires your approval.",
        "reference_type": Reference_Type_Enum.ASSET,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "ISSUE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Issue_Status_Enum.REPLACEMENT_REQUIRED,
        "notification_type": Notification_Type_Enum.REPLACEMENT_APPROVAL_NEEDED,
        "target_role": User_Role_Enum.MANAGEMENT,
        "recipient_field": None,
        "title": "Replacement Approval Needed",
        "message_template": "Issue {reference_id} requires replacement approval.",
        "reference_type": Reference_Type_Enum.ISSUE,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "SOFTWARE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Software_Status_Enum.ESCALATED_TO_MANAGEMENT,
        "notification_type": Notification_Type_Enum.SOFTWARE_INSTALL_ESCALATION,
        "target_role": User_Role_Enum.MANAGEMENT,
        "recipient_field": None,
        "title": "Software Install Escalation",
        "message_template": "Software request {reference_id} has been escalated to management.",
        "reference_type": Reference_Type_Enum.SOFTWARE,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "METADATA",
        "status_field": "Status",
        "from_status": None,
        "to_status": Asset_Status_Enum.DISPOSAL_PENDING,
        "notification_type": Notification_Type_Enum.DISPOSAL_APPROVAL_NEEDED,
        "target_role": User_Role_Enum.MANAGEMENT,
        "recipient_field": None,
        "title": "Disposal Approval Needed",
        "message_template": "Asset {reference_id} requires disposal approval.",
        "reference_type": Reference_Type_Enum.ASSET,
    },
    # =========================================================================
    # IT ADMIN role-based notifications
    # =========================================================================
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "METADATA",
        "status_field": "Status",
        "from_status": Asset_Status_Enum.ASSET_PENDING_APPROVAL,
        "to_status": Asset_Status_Enum.IN_STOCK,
        "notification_type": Notification_Type_Enum.ASSET_APPROVED,
        "target_role": User_Role_Enum.IT_ADMIN,
        "recipient_field": None,
        "title": "Asset Approved",
        "message_template": "Asset {reference_id} has been approved.",
        "reference_type": Reference_Type_Enum.ASSET,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "METADATA",
        "status_field": "Status",
        "from_status": Asset_Status_Enum.ASSET_PENDING_APPROVAL,
        "to_status": Asset_Status_Enum.ASSET_REJECTED,
        "notification_type": Notification_Type_Enum.ASSET_REJECTED,
        "target_role": User_Role_Enum.IT_ADMIN,
        "recipient_field": None,
        "title": "Asset Rejected",
        "message_template": "Asset {reference_id} has been rejected.",
        "reference_type": Reference_Type_Enum.ASSET,
    },
    {
        "trigger_type": "INSERT",
        "entity_prefix": "ISSUE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Issue_Status_Enum.TROUBLESHOOTING,
        "notification_type": Notification_Type_Enum.NEW_ISSUE_REPORTED,
        "target_role": User_Role_Enum.IT_ADMIN,
        "recipient_field": None,
        "title": "New Issue Reported",
        "message_template": "A new issue {reference_id} has been reported.",
        "reference_type": Reference_Type_Enum.ISSUE,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "ISSUE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Issue_Status_Enum.REPLACEMENT_APPROVED,
        "notification_type": Notification_Type_Enum.REPLACEMENT_APPROVED,
        "target_role": User_Role_Enum.IT_ADMIN,
        "recipient_field": None,
        "title": "Replacement Approved",
        "message_template": "Replacement for issue {reference_id} has been approved.",
        "reference_type": Reference_Type_Enum.ISSUE,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "ISSUE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Issue_Status_Enum.REPLACEMENT_REJECTED,
        "notification_type": Notification_Type_Enum.REPLACEMENT_REJECTED,
        "target_role": User_Role_Enum.IT_ADMIN,
        "recipient_field": None,
        "title": "Replacement Rejected",
        "message_template": "Replacement for issue {reference_id} has been rejected.",
        "reference_type": Reference_Type_Enum.ISSUE,
    },
    {
        "trigger_type": "INSERT",
        "entity_prefix": "SOFTWARE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Software_Status_Enum.PENDING_REVIEW,
        "notification_type": Notification_Type_Enum.NEW_SOFTWARE_INSTALL_REQUEST,
        "target_role": User_Role_Enum.IT_ADMIN,
        "recipient_field": None,
        "title": "New Software Install Request",
        "message_template": "A new software install request {reference_id} needs review.",
        "reference_type": Reference_Type_Enum.SOFTWARE,
    },
    {
        "trigger_type": "FIELD_CHANGE",
        "entity_prefix": "HANDOVER#",
        "status_field": "AcceptedAt",
        "from_status": None,
        "to_status": None,
        "notification_type": Notification_Type_Enum.HANDOVER_ACCEPTED,
        "target_role": User_Role_Enum.IT_ADMIN,
        "recipient_field": None,
        "title": "Handover Accepted",
        "message_template": "Handover for asset {reference_id} has been accepted by the employee.",
        "reference_type": Reference_Type_Enum.ASSET,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "AUDIT#",
        "status_field": "Status",
        "from_status": None,
        "to_status": "AUDIT_DISPUTED",
        "notification_type": Notification_Type_Enum.AUDIT_DISPUTE_RAISED,
        "target_role": User_Role_Enum.IT_ADMIN,
        "recipient_field": None,
        "title": "Audit Dispute Raised",
        "message_template": "An audit dispute has been raised for {reference_id}.",
        "reference_type": Reference_Type_Enum.AUDIT,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "AUDIT#",
        "status_field": "Status",
        "from_status": None,
        "to_status": "AUDIT_ESCALATED",
        "notification_type": Notification_Type_Enum.AUDIT_NON_RESPONSE_ESCALATION,
        "target_role": User_Role_Enum.IT_ADMIN,
        "recipient_field": None,
        "title": "Audit Non-Response Escalation",
        "message_template": "Audit {reference_id} has been escalated due to non-response.",
        "reference_type": Reference_Type_Enum.AUDIT,
    },
    # =========================================================================
    # EMPLOYEE user-specific notifications (target_role=None)
    # =========================================================================
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "METADATA",
        "status_field": "Status",
        "from_status": None,
        "to_status": Asset_Status_Enum.ASSIGNED,
        "notification_type": Notification_Type_Enum.NEW_ASSET_ASSIGNED,
        "target_role": None,
        "recipient_field": "EmployeeAssetIndexPK",
        "title": "New Asset Assigned",
        "message_template": "Asset {reference_id} has been assigned to you.",
        "reference_type": Reference_Type_Enum.ASSET,
    },
    {
        "trigger_type": "INSERT",
        "entity_prefix": "HANDOVER#",
        "status_field": None,
        "from_status": None,
        "to_status": None,
        "notification_type": Notification_Type_Enum.HANDOVER_FORM_READY,
        "target_role": None,
        "recipient_field": "EmployeeID",
        "title": "Handover Form Ready",
        "message_template": "A handover form for asset {reference_id} is ready for your review.",
        "reference_type": Reference_Type_Enum.ASSET,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "SOFTWARE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Software_Status_Enum.SOFTWARE_INSTALL_APPROVED,
        "notification_type": Notification_Type_Enum.SOFTWARE_INSTALL_APPROVED,
        "target_role": None,
        "recipient_field": "RequestedBy",
        "title": "Software Install Approved",
        "message_template": "Your software install request {reference_id} has been approved.",
        "reference_type": Reference_Type_Enum.SOFTWARE,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "SOFTWARE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Software_Status_Enum.SOFTWARE_INSTALL_REJECTED,
        "notification_type": Notification_Type_Enum.SOFTWARE_INSTALL_REJECTED,
        "target_role": None,
        "recipient_field": "RequestedBy",
        "title": "Software Install Rejected",
        "message_template": "Your software install request {reference_id} has been rejected.",
        "reference_type": Reference_Type_Enum.SOFTWARE,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "ISSUE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Issue_Status_Enum.UNDER_REPAIR,
        "notification_type": Notification_Type_Enum.ISSUE_UNDER_REPAIR,
        "target_role": None,
        "recipient_field": "ReportedBy",
        "title": "Issue Under Repair",
        "message_template": "Your reported issue {reference_id} is now under repair.",
        "reference_type": Reference_Type_Enum.ISSUE,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "ISSUE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Issue_Status_Enum.SEND_WARRANTY,
        "notification_type": Notification_Type_Enum.ISSUE_SENT_TO_WARRANTY,
        "target_role": None,
        "recipient_field": "ReportedBy",
        "title": "Issue Sent to Warranty",
        "message_template": "Your reported issue {reference_id} has been sent for warranty service.",
        "reference_type": Reference_Type_Enum.ISSUE,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "ISSUE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Issue_Status_Enum.RESOLVED,
        "notification_type": Notification_Type_Enum.ISSUE_RESOLVED,
        "target_role": None,
        "recipient_field": "ReportedBy",
        "title": "Issue Resolved",
        "message_template": "Your reported issue {reference_id} has been resolved.",
        "reference_type": Reference_Type_Enum.ISSUE,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "METADATA",
        "status_field": "Status",
        "from_status": None,
        "to_status": Asset_Status_Enum.RETURN_PENDING,
        "notification_type": Notification_Type_Enum.RETURN_INITIATED,
        "target_role": None,
        "recipient_field": "EmployeeAssetIndexPK",
        "title": "Return Initiated",
        "message_template": "A return has been initiated for asset {reference_id}.",
        "reference_type": Reference_Type_Enum.RETURN,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "AUDIT#",
        "status_field": "Status",
        "from_status": None,
        "to_status": "AWAITING_EMPLOYEE_CONFIRMATION",
        "notification_type": Notification_Type_Enum.AUDIT_CONFIRMATION_REQUIRED,
        "target_role": None,
        "recipient_field": "EmployeeID",
        "title": "Audit Confirmation Required",
        "message_template": "Audit {reference_id} requires your confirmation.",
        "reference_type": Reference_Type_Enum.AUDIT,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "AUDIT#",
        "status_field": "Status",
        "from_status": None,
        "to_status": "AWAITING_FINAL_ACKNOWLEDGEMENT",
        "notification_type": Notification_Type_Enum.AUDIT_FINAL_ACKNOWLEDGEMENT,
        "target_role": None,
        "recipient_field": "EmployeeID",
        "title": "Audit Final Acknowledgement",
        "message_template": "Audit {reference_id} requires your final acknowledgement.",
        "reference_type": Reference_Type_Enum.AUDIT,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "AUDIT#",
        "status_field": "Status",
        "from_status": None,
        "to_status": "AUDIT_ADMIN_REVIEWED",
        "notification_type": Notification_Type_Enum.AUDIT_DISPUTE_REVIEWED,
        "target_role": None,
        "recipient_field": "EmployeeID",
        "title": "Audit Dispute Reviewed",
        "message_template": "Your audit dispute for {reference_id} has been reviewed by an admin.",
        "reference_type": Reference_Type_Enum.AUDIT,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "AUDIT#",
        "status_field": "Status",
        "from_status": None,
        "to_status": "AUDIT_REMINDER",
        "notification_type": Notification_Type_Enum.AUDIT_REMINDER,
        "target_role": None,
        "recipient_field": "EmployeeID",
        "title": "Audit Reminder",
        "message_template": "Reminder: Audit {reference_id} is awaiting your response.",
        "reference_type": Reference_Type_Enum.AUDIT,
    },
    # =========================================================================
    # FINANCE role-based notifications
    # =========================================================================
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "METADATA",
        "status_field": "Status",
        "from_status": None,
        "to_status": Asset_Status_Enum.DISPOSED,
        "notification_type": Notification_Type_Enum.ASSET_DISPOSED_WRITEOFF,
        "target_role": User_Role_Enum.FINANCE,
        "recipient_field": None,
        "title": "Asset Disposed — Write-Off",
        "message_template": "Asset {reference_id} has been disposed and may require financial write-off.",
        "reference_type": Reference_Type_Enum.ASSET,
    },
    {
        "trigger_type": "STATUS_CHANGE",
        "entity_prefix": "ISSUE#",
        "status_field": "Status",
        "from_status": None,
        "to_status": Issue_Status_Enum.REPLACEMENT_APPROVED,
        "notification_type": Notification_Type_Enum.REPLACEMENT_APPROVED_INFO,
        "target_role": User_Role_Enum.FINANCE,
        "recipient_field": None,
        "title": "Replacement Approved — Finance Info",
        "message_template": "Replacement for issue {reference_id} has been approved. Budget impact may apply.",
        "reference_type": Reference_Type_Enum.ISSUE,
    },
]
