/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as NewPasswordRouteImport } from './routes/new-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedPendingSignaturesRouteImport } from './routes/_authenticated/pending-signatures'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedRequestsNewSoftwareRouteImport } from './routes/_authenticated/requests.new-software'
import { Route as AuthenticatedRequestsNewIssueRouteImport } from './routes/_authenticated/requests.new-issue'
import { Route as AuthenticatedAssetsNewRouteImport } from './routes/_authenticated/assets.new'
import { Route as AuthenticatedAssetsAsset_idRouteImport } from './routes/_authenticated/assets.$asset_id'
import { Route as AuthenticatedAssetsAsset_idSoftwareRequestsRouteImport } from './routes/_authenticated/assets.$asset_id.software-requests'
import { Route as AuthenticatedAssetsAsset_idApproveRouteImport } from './routes/_authenticated/assets.$asset_id.approve'
import { Route as AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRouteImport } from './routes/_authenticated/assets.$asset_id.software-requests.$software_request_id'
import { Route as AuthenticatedAssetsAsset_idReturnsReturn_idRouteImport } from './routes/_authenticated/assets.$asset_id.returns.$return_id'
import { Route as AuthenticatedAssetsAsset_idIssuesIssue_idRouteImport } from './routes/_authenticated/assets.$asset_id.issues.$issue_id'
import { Route as AuthenticatedAssetsAsset_idDisposalsDisposal_idRouteImport } from './routes/_authenticated/assets.$asset_id.disposals.$disposal_id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPasswordRoute = NewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendingSignaturesRoute =
  AuthenticatedPendingSignaturesRouteImport.update({
    id: '/pending-signatures',
    path: '/pending-signatures',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestsNewSoftwareRoute =
  AuthenticatedRequestsNewSoftwareRouteImport.update({
    id: '/new-software',
    path: '/new-software',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AuthenticatedRequestsNewIssueRoute =
  AuthenticatedRequestsNewIssueRouteImport.update({
    id: '/new-issue',
    path: '/new-issue',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AuthenticatedAssetsNewRoute = AuthenticatedAssetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAssetsRoute,
} as any)
const AuthenticatedAssetsAsset_idRoute =
  AuthenticatedAssetsAsset_idRouteImport.update({
    id: '/$asset_id',
    path: '/$asset_id',
    getParentRoute: () => AuthenticatedAssetsRoute,
  } as any)
const AuthenticatedAssetsAsset_idSoftwareRequestsRoute =
  AuthenticatedAssetsAsset_idSoftwareRequestsRouteImport.update({
    id: '/software-requests',
    path: '/software-requests',
    getParentRoute: () => AuthenticatedAssetsAsset_idRoute,
  } as any)
const AuthenticatedAssetsAsset_idApproveRoute =
  AuthenticatedAssetsAsset_idApproveRouteImport.update({
    id: '/approve',
    path: '/approve',
    getParentRoute: () => AuthenticatedAssetsAsset_idRoute,
  } as any)
const AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRoute =
  AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRouteImport.update(
    {
      id: '/$software_request_id',
      path: '/$software_request_id',
      getParentRoute: () => AuthenticatedAssetsAsset_idSoftwareRequestsRoute,
    } as any,
  )
const AuthenticatedAssetsAsset_idReturnsReturn_idRoute =
  AuthenticatedAssetsAsset_idReturnsReturn_idRouteImport.update({
    id: '/returns/$return_id',
    path: '/returns/$return_id',
    getParentRoute: () => AuthenticatedAssetsAsset_idRoute,
  } as any)
const AuthenticatedAssetsAsset_idIssuesIssue_idRoute =
  AuthenticatedAssetsAsset_idIssuesIssue_idRouteImport.update({
    id: '/issues/$issue_id',
    path: '/issues/$issue_id',
    getParentRoute: () => AuthenticatedAssetsAsset_idRoute,
  } as any)
const AuthenticatedAssetsAsset_idDisposalsDisposal_idRoute =
  AuthenticatedAssetsAsset_idDisposalsDisposal_idRouteImport.update({
    id: '/disposals/$disposal_id',
    path: '/disposals/$disposal_id',
    getParentRoute: () => AuthenticatedAssetsAsset_idRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new-password': typeof NewPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/pending-signatures': typeof AuthenticatedPendingSignaturesRoute
  '/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/assets/$asset_id': typeof AuthenticatedAssetsAsset_idRouteWithChildren
  '/assets/new': typeof AuthenticatedAssetsNewRoute
  '/requests/new-issue': typeof AuthenticatedRequestsNewIssueRoute
  '/requests/new-software': typeof AuthenticatedRequestsNewSoftwareRoute
  '/assets/$asset_id/approve': typeof AuthenticatedAssetsAsset_idApproveRoute
  '/assets/$asset_id/software-requests': typeof AuthenticatedAssetsAsset_idSoftwareRequestsRouteWithChildren
  '/assets/$asset_id/disposals/$disposal_id': typeof AuthenticatedAssetsAsset_idDisposalsDisposal_idRoute
  '/assets/$asset_id/issues/$issue_id': typeof AuthenticatedAssetsAsset_idIssuesIssue_idRoute
  '/assets/$asset_id/returns/$return_id': typeof AuthenticatedAssetsAsset_idReturnsReturn_idRoute
  '/assets/$asset_id/software-requests/$software_request_id': typeof AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new-password': typeof NewPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/pending-signatures': typeof AuthenticatedPendingSignaturesRoute
  '/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/assets/$asset_id': typeof AuthenticatedAssetsAsset_idRouteWithChildren
  '/assets/new': typeof AuthenticatedAssetsNewRoute
  '/requests/new-issue': typeof AuthenticatedRequestsNewIssueRoute
  '/requests/new-software': typeof AuthenticatedRequestsNewSoftwareRoute
  '/assets/$asset_id/approve': typeof AuthenticatedAssetsAsset_idApproveRoute
  '/assets/$asset_id/software-requests': typeof AuthenticatedAssetsAsset_idSoftwareRequestsRouteWithChildren
  '/assets/$asset_id/disposals/$disposal_id': typeof AuthenticatedAssetsAsset_idDisposalsDisposal_idRoute
  '/assets/$asset_id/issues/$issue_id': typeof AuthenticatedAssetsAsset_idIssuesIssue_idRoute
  '/assets/$asset_id/returns/$return_id': typeof AuthenticatedAssetsAsset_idReturnsReturn_idRoute
  '/assets/$asset_id/software-requests/$software_request_id': typeof AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new-password': typeof NewPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/_authenticated/pending-signatures': typeof AuthenticatedPendingSignaturesRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/assets/$asset_id': typeof AuthenticatedAssetsAsset_idRouteWithChildren
  '/_authenticated/assets/new': typeof AuthenticatedAssetsNewRoute
  '/_authenticated/requests/new-issue': typeof AuthenticatedRequestsNewIssueRoute
  '/_authenticated/requests/new-software': typeof AuthenticatedRequestsNewSoftwareRoute
  '/_authenticated/assets/$asset_id/approve': typeof AuthenticatedAssetsAsset_idApproveRoute
  '/_authenticated/assets/$asset_id/software-requests': typeof AuthenticatedAssetsAsset_idSoftwareRequestsRouteWithChildren
  '/_authenticated/assets/$asset_id/disposals/$disposal_id': typeof AuthenticatedAssetsAsset_idDisposalsDisposal_idRoute
  '/_authenticated/assets/$asset_id/issues/$issue_id': typeof AuthenticatedAssetsAsset_idIssuesIssue_idRoute
  '/_authenticated/assets/$asset_id/returns/$return_id': typeof AuthenticatedAssetsAsset_idReturnsReturn_idRoute
  '/_authenticated/assets/$asset_id/software-requests/$software_request_id': typeof AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/new-password'
    | '/unauthorized'
    | '/approvals'
    | '/assets'
    | '/pending-signatures'
    | '/requests'
    | '/users'
    | '/'
    | '/assets/$asset_id'
    | '/assets/new'
    | '/requests/new-issue'
    | '/requests/new-software'
    | '/assets/$asset_id/approve'
    | '/assets/$asset_id/software-requests'
    | '/assets/$asset_id/disposals/$disposal_id'
    | '/assets/$asset_id/issues/$issue_id'
    | '/assets/$asset_id/returns/$return_id'
    | '/assets/$asset_id/software-requests/$software_request_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/new-password'
    | '/unauthorized'
    | '/approvals'
    | '/assets'
    | '/pending-signatures'
    | '/requests'
    | '/users'
    | '/'
    | '/assets/$asset_id'
    | '/assets/new'
    | '/requests/new-issue'
    | '/requests/new-software'
    | '/assets/$asset_id/approve'
    | '/assets/$asset_id/software-requests'
    | '/assets/$asset_id/disposals/$disposal_id'
    | '/assets/$asset_id/issues/$issue_id'
    | '/assets/$asset_id/returns/$return_id'
    | '/assets/$asset_id/software-requests/$software_request_id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/new-password'
    | '/unauthorized'
    | '/_authenticated/approvals'
    | '/_authenticated/assets'
    | '/_authenticated/pending-signatures'
    | '/_authenticated/requests'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/assets/$asset_id'
    | '/_authenticated/assets/new'
    | '/_authenticated/requests/new-issue'
    | '/_authenticated/requests/new-software'
    | '/_authenticated/assets/$asset_id/approve'
    | '/_authenticated/assets/$asset_id/software-requests'
    | '/_authenticated/assets/$asset_id/disposals/$disposal_id'
    | '/_authenticated/assets/$asset_id/issues/$issue_id'
    | '/_authenticated/assets/$asset_id/returns/$return_id'
    | '/_authenticated/assets/$asset_id/software-requests/$software_request_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NewPasswordRoute: typeof NewPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-password': {
      id: '/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof NewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pending-signatures': {
      id: '/_authenticated/pending-signatures'
      path: '/pending-signatures'
      fullPath: '/pending-signatures'
      preLoaderRoute: typeof AuthenticatedPendingSignaturesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/new-software': {
      id: '/_authenticated/requests/new-software'
      path: '/new-software'
      fullPath: '/requests/new-software'
      preLoaderRoute: typeof AuthenticatedRequestsNewSoftwareRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_authenticated/requests/new-issue': {
      id: '/_authenticated/requests/new-issue'
      path: '/new-issue'
      fullPath: '/requests/new-issue'
      preLoaderRoute: typeof AuthenticatedRequestsNewIssueRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_authenticated/assets/new': {
      id: '/_authenticated/assets/new'
      path: '/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AuthenticatedAssetsNewRouteImport
      parentRoute: typeof AuthenticatedAssetsRoute
    }
    '/_authenticated/assets/$asset_id': {
      id: '/_authenticated/assets/$asset_id'
      path: '/$asset_id'
      fullPath: '/assets/$asset_id'
      preLoaderRoute: typeof AuthenticatedAssetsAsset_idRouteImport
      parentRoute: typeof AuthenticatedAssetsRoute
    }
    '/_authenticated/assets/$asset_id/software-requests': {
      id: '/_authenticated/assets/$asset_id/software-requests'
      path: '/software-requests'
      fullPath: '/assets/$asset_id/software-requests'
      preLoaderRoute: typeof AuthenticatedAssetsAsset_idSoftwareRequestsRouteImport
      parentRoute: typeof AuthenticatedAssetsAsset_idRoute
    }
    '/_authenticated/assets/$asset_id/approve': {
      id: '/_authenticated/assets/$asset_id/approve'
      path: '/approve'
      fullPath: '/assets/$asset_id/approve'
      preLoaderRoute: typeof AuthenticatedAssetsAsset_idApproveRouteImport
      parentRoute: typeof AuthenticatedAssetsAsset_idRoute
    }
    '/_authenticated/assets/$asset_id/software-requests/$software_request_id': {
      id: '/_authenticated/assets/$asset_id/software-requests/$software_request_id'
      path: '/$software_request_id'
      fullPath: '/assets/$asset_id/software-requests/$software_request_id'
      preLoaderRoute: typeof AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRouteImport
      parentRoute: typeof AuthenticatedAssetsAsset_idSoftwareRequestsRoute
    }
    '/_authenticated/assets/$asset_id/returns/$return_id': {
      id: '/_authenticated/assets/$asset_id/returns/$return_id'
      path: '/returns/$return_id'
      fullPath: '/assets/$asset_id/returns/$return_id'
      preLoaderRoute: typeof AuthenticatedAssetsAsset_idReturnsReturn_idRouteImport
      parentRoute: typeof AuthenticatedAssetsAsset_idRoute
    }
    '/_authenticated/assets/$asset_id/issues/$issue_id': {
      id: '/_authenticated/assets/$asset_id/issues/$issue_id'
      path: '/issues/$issue_id'
      fullPath: '/assets/$asset_id/issues/$issue_id'
      preLoaderRoute: typeof AuthenticatedAssetsAsset_idIssuesIssue_idRouteImport
      parentRoute: typeof AuthenticatedAssetsAsset_idRoute
    }
    '/_authenticated/assets/$asset_id/disposals/$disposal_id': {
      id: '/_authenticated/assets/$asset_id/disposals/$disposal_id'
      path: '/disposals/$disposal_id'
      fullPath: '/assets/$asset_id/disposals/$disposal_id'
      preLoaderRoute: typeof AuthenticatedAssetsAsset_idDisposalsDisposal_idRouteImport
      parentRoute: typeof AuthenticatedAssetsAsset_idRoute
    }
  }
}

interface AuthenticatedAssetsAsset_idSoftwareRequestsRouteChildren {
  AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRoute: typeof AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRoute
}

const AuthenticatedAssetsAsset_idSoftwareRequestsRouteChildren: AuthenticatedAssetsAsset_idSoftwareRequestsRouteChildren =
  {
    AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRoute:
      AuthenticatedAssetsAsset_idSoftwareRequestsSoftware_request_idRoute,
  }

const AuthenticatedAssetsAsset_idSoftwareRequestsRouteWithChildren =
  AuthenticatedAssetsAsset_idSoftwareRequestsRoute._addFileChildren(
    AuthenticatedAssetsAsset_idSoftwareRequestsRouteChildren,
  )

interface AuthenticatedAssetsAsset_idRouteChildren {
  AuthenticatedAssetsAsset_idApproveRoute: typeof AuthenticatedAssetsAsset_idApproveRoute
  AuthenticatedAssetsAsset_idSoftwareRequestsRoute: typeof AuthenticatedAssetsAsset_idSoftwareRequestsRouteWithChildren
  AuthenticatedAssetsAsset_idDisposalsDisposal_idRoute: typeof AuthenticatedAssetsAsset_idDisposalsDisposal_idRoute
  AuthenticatedAssetsAsset_idIssuesIssue_idRoute: typeof AuthenticatedAssetsAsset_idIssuesIssue_idRoute
  AuthenticatedAssetsAsset_idReturnsReturn_idRoute: typeof AuthenticatedAssetsAsset_idReturnsReturn_idRoute
}

const AuthenticatedAssetsAsset_idRouteChildren: AuthenticatedAssetsAsset_idRouteChildren =
  {
    AuthenticatedAssetsAsset_idApproveRoute:
      AuthenticatedAssetsAsset_idApproveRoute,
    AuthenticatedAssetsAsset_idSoftwareRequestsRoute:
      AuthenticatedAssetsAsset_idSoftwareRequestsRouteWithChildren,
    AuthenticatedAssetsAsset_idDisposalsDisposal_idRoute:
      AuthenticatedAssetsAsset_idDisposalsDisposal_idRoute,
    AuthenticatedAssetsAsset_idIssuesIssue_idRoute:
      AuthenticatedAssetsAsset_idIssuesIssue_idRoute,
    AuthenticatedAssetsAsset_idReturnsReturn_idRoute:
      AuthenticatedAssetsAsset_idReturnsReturn_idRoute,
  }

const AuthenticatedAssetsAsset_idRouteWithChildren =
  AuthenticatedAssetsAsset_idRoute._addFileChildren(
    AuthenticatedAssetsAsset_idRouteChildren,
  )

interface AuthenticatedAssetsRouteChildren {
  AuthenticatedAssetsAsset_idRoute: typeof AuthenticatedAssetsAsset_idRouteWithChildren
  AuthenticatedAssetsNewRoute: typeof AuthenticatedAssetsNewRoute
}

const AuthenticatedAssetsRouteChildren: AuthenticatedAssetsRouteChildren = {
  AuthenticatedAssetsAsset_idRoute:
    AuthenticatedAssetsAsset_idRouteWithChildren,
  AuthenticatedAssetsNewRoute: AuthenticatedAssetsNewRoute,
}

const AuthenticatedAssetsRouteWithChildren =
  AuthenticatedAssetsRoute._addFileChildren(AuthenticatedAssetsRouteChildren)

interface AuthenticatedRequestsRouteChildren {
  AuthenticatedRequestsNewIssueRoute: typeof AuthenticatedRequestsNewIssueRoute
  AuthenticatedRequestsNewSoftwareRoute: typeof AuthenticatedRequestsNewSoftwareRoute
}

const AuthenticatedRequestsRouteChildren: AuthenticatedRequestsRouteChildren = {
  AuthenticatedRequestsNewIssueRoute: AuthenticatedRequestsNewIssueRoute,
  AuthenticatedRequestsNewSoftwareRoute: AuthenticatedRequestsNewSoftwareRoute,
}

const AuthenticatedRequestsRouteWithChildren =
  AuthenticatedRequestsRoute._addFileChildren(
    AuthenticatedRequestsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRouteWithChildren
  AuthenticatedPendingSignaturesRoute: typeof AuthenticatedPendingSignaturesRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRouteWithChildren,
  AuthenticatedPendingSignaturesRoute: AuthenticatedPendingSignaturesRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NewPasswordRoute: NewPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
